:title: "Eddie Samuels"
:headline:
:body: |
    I make hardware!

    *Previously:* worked on the [panda](https://techcrunch.com/2017/07/07/comma-ai-launches-an-88-universal-car-interface-called-panda/) OBDII interface and the [eon](https://www.engadget.com/2017/10/24/comma-ai-eon-autonomous-future/) driver development kit at comma.ai

    ***Currently:*** **accepting gigs @[studlabs](https://studlabs.com)**

    Check out my [resume](/resume.pdf)

    Thanks for stopping by!
